############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Showcase"
url = "/en/showcase"
weight = 2

[[main]]
name = "Prices"
url = "/en/prices"
weight = 4


[[main]]
name = "About Us"
url = "/en/about"
weight = 3


# footer menu
[[footer]]
name = "About Us"
url = "/en/about"
weight = 1

[[footer]]
name = "Mentions légales "
url = "/en/mentions-legales "
weight = 2




